// Generated by scripts/export_strategy_venue_registry.py. Do not edit by hand.
export const VENUE_REGISTRY = {
  "schema_version": 1,
  "registry_version": "2026-09-12.2",
  "source": "noahai_client.trading.exchanges.venue_capabilities",
  "venues": [
    {
      "id": "binance",
      "client_id": "binance",
      "aliases": [
        "binance"
      ],
      "display_name": "Binance",
      "service": "blockchain",
      "asset_class": "crypto",
      "market_type": "futures",
      "instrument_group": "perpetual_futures",
      "quote_currency": "USDT",
      "can_short": true,
      "can_leverage": true,
      "adapter_family": "native",
      "order_amount_unit": "base",
      "requires_contract_size": false,
      "onboarding_status": "live_ready",
      "paper_supported": true,
      "live_supported": true
    },
    {
      "id": "upbit",
      "client_id": "upbit",
      "aliases": [
        "upbit"
      ],
      "display_name": "Upbit",
      "service": "blockchain",
      "asset_class": "crypto",
      "market_type": "spot",
      "instrument_group": "cash_spot",
      "quote_currency": "KRW",
      "can_short": false,
      "can_leverage": false,
      "adapter_family": "ccxt",
      "order_amount_unit": "quote_on_market_buy",
      "requires_contract_size": false,
      "onboarding_status": "live_ready",
      "paper_supported": true,
      "live_supported": true
    },
    {
      "id": "bithumb",
      "client_id": "bithumb",
      "aliases": [
        "bithumb"
      ],
      "display_name": "Bithumb",
      "service": "blockchain",
      "asset_class": "crypto",
      "market_type": "spot",
      "instrument_group": "cash_spot",
      "quote_currency": "KRW",
      "can_short": false,
      "can_leverage": false,
      "adapter_family": "ccxt",
      "order_amount_unit": "base",
      "requires_contract_size": false,
      "onboarding_status": "live_ready",
      "paper_supported": true,
      "live_supported": true
    },
    {
      "id": "coinone",
      "client_id": "coinone",
      "aliases": [
        "coinone"
      ],
      "display_name": "Coinone",
      "service": "blockchain",
      "asset_class": "crypto",
      "market_type": "spot",
      "instrument_group": "cash_spot",
      "quote_currency": "KRW",
      "can_short": false,
      "can_leverage": false,
      "adapter_family": "ccxt_hybrid",
      "order_amount_unit": "quote_on_market_buy",
      "requires_contract_size": false,
      "onboarding_status": "live_ready",
      "paper_supported": true,
      "live_supported": true
    },
    {
      "id": "bybit",
      "client_id": "bybit",
      "aliases": [
        "bybit"
      ],
      "display_name": "Bybit",
      "service": "blockchain",
      "asset_class": "crypto",
      "market_type": "futures",
      "instrument_group": "perpetual_futures",
      "quote_currency": "USDT",
      "can_short": true,
      "can_leverage": true,
      "adapter_family": "ccxt",
      "order_amount_unit": "contracts",
      "requires_contract_size": true,
      "onboarding_status": "live_ready",
      "paper_supported": true,
      "live_supported": true
    },
    {
      "id": "okx",
      "client_id": "okx",
      "aliases": [
        "okx"
      ],
      "display_name": "OKX",
      "service": "blockchain",
      "asset_class": "crypto",
      "market_type": "futures",
      "instrument_group": "perpetual_futures",
      "quote_currency": "USDT",
      "can_short": true,
      "can_leverage": true,
      "adapter_family": "ccxt",
      "order_amount_unit": "contracts",
      "requires_contract_size": true,
      "onboarding_status": "live_ready",
      "paper_supported": true,
      "live_supported": true
    },
    {
      "id": "bitget",
      "client_id": "bitget",
      "aliases": [
        "bitget"
      ],
      "display_name": "Bitget",
      "service": "blockchain",
      "asset_class": "crypto",
      "market_type": "futures",
      "instrument_group": "perpetual_futures",
      "quote_currency": "USDT",
      "can_short": true,
      "can_leverage": true,
      "adapter_family": "ccxt",
      "order_amount_unit": "contracts",
      "requires_contract_size": true,
      "onboarding_status": "live_ready",
      "paper_supported": true,
      "live_supported": true
    },
    {
      "id": "kiwoom",
      "client_id": "kiwoom",
      "aliases": [
        "kiwoom"
      ],
      "display_name": "키움증권",
      "service": "stock",
      "asset_class": "stock",
      "market_type": "stock",
      "instrument_group": "cash_stock_etf",
      "quote_currency": "KRW",
      "can_short": false,
      "can_leverage": false,
      "adapter_family": "broker_native",
      "order_amount_unit": "whole_shares",
      "requires_contract_size": false,
      "onboarding_status": "live_ready",
      "paper_supported": true,
      "live_supported": true
    },
    {
      "id": "shinhan",
      "client_id": "shinhan",
      "aliases": [
        "shinhan"
      ],
      "display_name": "신한투자증권",
      "service": "stock",
      "asset_class": "stock",
      "market_type": "stock",
      "instrument_group": "cash_stock_etf",
      "quote_currency": "KRW",
      "can_short": false,
      "can_leverage": false,
      "adapter_family": "broker_native",
      "order_amount_unit": "whole_shares",
      "requires_contract_size": false,
      "onboarding_status": "live_ready",
      "paper_supported": true,
      "live_supported": true
    },
    {
      "id": "miraeasset",
      "client_id": "mirae",
      "aliases": [
        "miraeasset",
        "mirae"
      ],
      "display_name": "미래에셋증권",
      "service": "stock",
      "asset_class": "stock",
      "market_type": "stock",
      "instrument_group": "cash_stock_etf",
      "quote_currency": "KRW",
      "can_short": false,
      "can_leverage": false,
      "adapter_family": "broker_native",
      "order_amount_unit": "whole_shares",
      "requires_contract_size": false,
      "onboarding_status": "live_ready",
      "paper_supported": true,
      "live_supported": true
    },
    {
      "id": "koreainvestment",
      "client_id": "kis",
      "aliases": [
        "koreainvestment",
        "kis"
      ],
      "display_name": "한국투자증권",
      "service": "stock",
      "asset_class": "stock",
      "market_type": "stock",
      "instrument_group": "cash_stock_etf",
      "quote_currency": "KRW",
      "can_short": false,
      "can_leverage": false,
      "adapter_family": "broker_native",
      "order_amount_unit": "whole_shares",
      "requires_contract_size": false,
      "onboarding_status": "live_ready",
      "paper_supported": true,
      "live_supported": true
    }
  ]
} as const;
export type PublicVenueProfile = (typeof VENUE_REGISTRY.venues)[number];
