# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('config/settings_template.json', 'config'),
        ('config/token_template.json', 'config'),
        ('config/theme_config.json', 'config'),
        ('docs', 'docs'),
    # UI Python modules are auto-discovered via imports; do not bundle entire ui folder
        ('trading', 'trading'),
        ('trading/ai', 'trading/ai'),
        ('trading/exchanges', 'trading/exchanges'),
        ('trading/exchange_manager.py', 'trading'),
        ('trading/api_signal_manager.py', 'trading'),
        ('api', 'api'),
        ('log_system', 'log_system'),  # 프로젝트 로깅 모듈
        ('utils', 'utils'),  # 시간 동기화 및 유틸리티 모듈
        ('strategy_customizer.py', '.'),
        ('ai_chat_strategy.py', '.'),
        ('path_check.py', '.'),
        ('web_deployment_analysis.py', '.'),
        ('user_status_manager.py', '.'),
        ('path_utils.py', '.'),
        ('README.md', '.'),
        ('requirements.txt', '.'),
        ('requirements_windows.txt', '.'),
        ('icon.ico', '.'),
        ('icon.png', '.'),

    ],
    hiddenimports=[
        'tkinter',
        'tkinter.ttk',
        'tkinter.messagebox',
        'tkinter.filedialog',
        'tkinter.colorchooser',
        'tkinter.simpledialog',
        'tkinter.font',
        'tkinter.constants',
    'customtkinter',
        'customtkinter.windows',
        'customtkinter.windows.ctk_tk',
        'websockets',
        'websocket',
        'websocket_client',
        'binance',
        'ccxt',
        'ccxt.binance',
        'ccxt.upbit',
        'ccxt.bithumb',
        'ccxt.bybit',
        'ccxt.okx',
        'ccxt.bitget',  # v3.7.8: 추가 거래소 명시적 포함
    'trading.exchange_manager',
    'trading.api_signal_manager',
    'trading.exchanges.exchange_factory',
    'trading.exchanges.adapters.kiwoom_stock_adapter',
    'trading.exchanges.adapters.stock_mock_adapter',
    'trading.exchanges.adapters.shinhan_stock_adapter',
    'trading.exchanges.adapters.mirae_asset_stock_adapter',
    'trading.exchanges.adapters.korea_investment_stock_adapter',
    # 키움증권 pykiwoom: PyQt5.QAxWidget 기반 — 반드시 명시적으로 포함해야 함
    'pykiwoom',
    'pykiwoom.kiwoom',
    'PyQt5',
    'PyQt5.QtWidgets',
    'PyQt5.QtCore',
    'PyQt5.QtGui',
    'PyQt5.QAxContainer',
    'theme_system',
    'theme_system.theme_manager',
    'theme_system.ui_components',
    'theme_system.color_palettes',
    'theme_system.font_system',
        # 🔥 표준 logging은 자동 포함되므로 제거 (충돌 방지)
        'openai',
        'numpy',
        'pandas',
        'loguru',
        'asyncio',
        'sqlite3',
        'json',
        'datetime',
        'requests',
        'threading',
        'queue',
        'time',
        'math',
        'random',
        'speech_recognition',
        'pyaudio',
        'statistics',
        'collections',
        'itertools',
        'functools',
        'typing',
        'dataclasses',
        'enum',
        'pathlib',
        'shutil',
        'subprocess',
        'sys',
        'os',
        'dotenv',
        'ujson',
        'aiohttp',
        'dateparser',
        'colorama',
        'win32_setctime',
        'psutil',
        # OCR 엔진 (차트 분석)
        'rapidocr_onnxruntime',
        'onnxruntime',
        'paddleocr',
        'paddlepaddle',
        'pypdf',
        'youtube_transcript_api',
        'yt_dlp',
    ],
    hookspath=['hooks'],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'matplotlib',
        'scipy',
        'scikit-learn',
        'tensorflow',
        'torch',
        'jupyter',
        'notebook',
        'ipython',
        'pytest',
        'unittest',
        'wx',
        'gtk',
        'qt4',
        'qt6',
        # PyQt5는 제외 불가: pykiwoom(키움증권 OpenAPI+)이 PyQt5.QAxWidget 기반
        # 'PyQt5',  ← 제거: pykiwoom 동작 불가 원인이었음
        'PySide6',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='AITrading',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,  # GUI mode (hide console window)
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='icon.ico',
    version='config/windows_version_info.txt',
)
