# -*- mode: python ; coding: utf-8 -*-
# AUTO-GENERATED BY build_safe.py. 직접 수정하지 마세요.

import sys

block_cipher = None

if sys.platform.startswith('win'):
    from build_safe import WINDOWS_VC_RUNTIME_NAMES, resolve_windows_vc_runtime_binaries
    _noahai_vc_runtime_binaries = resolve_windows_vc_runtime_binaries()
else:
    WINDOWS_VC_RUNTIME_NAMES = frozenset()
    _noahai_vc_runtime_binaries = []

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('config/settings_template.json', 'config'),
        ('config/token_template.json', 'config'),
        ('config/theme_config.json', 'config'),
        ('data/finance_products', 'data/finance_products'),
        ('docs', 'docs'),
        # Python 소스는 Analysis/hiddenimports가 수집한다. datas로 중복 번들하지 않는다.
        ('README.md', '.'),
        ('requirements.txt', '.'),
        ('requirements_windows.txt', '.'),
        ('icon.ico', '.') ,
        ('icon.png', '.') ,
        # 사용자 data는 제외하고 위의 읽기 전용 금융상품 기본 카탈로그만 포함
    ],
    hiddenimports=[
        'tkinter',
        'tkinter.ttk',
        'tkinter.messagebox',
        'customtkinter',
        'websockets',
        'websocket',
        'websocket_client',
        'binance',
        'ccxt',
        'ccxt.binance',
        'ccxt.upbit',
        'ccxt.bithumb',
        'ccxt.bybit',
        'ccxt.okx',
        'ccxt.bitget',
        'trading.exchange_manager',
        'trading.api_signal_manager',
        'trading.ai_custom_features',
        'trading.user_indicator_language',
        'trading.strategy_package',
        'trading.strategy_quality_report',
        'trading.signed_strategy_webhook',
        'referral_account_proof',
        'trading.exchanges.exchange_factory',
        'trading.exchanges.adapters.kiwoom_stock_adapter',
        'trading.exchanges.adapters.stock_mock_adapter',
        'trading.exchanges.adapters.shinhan_stock_adapter',
        'trading.exchanges.adapters.mirae_asset_stock_adapter',
        'trading.exchanges.adapters.korea_investment_stock_adapter',
        'openai',
        'numpy',
        'pandas',
        'loguru',
        'asyncio',
        'sqlite3',
        'json',
        'datetime',
        'requests',
        'threading',
        'queue',
        'time',
        'math',
        'random',
        'statistics',
        'collections',
        'itertools',
        'functools',
        'typing',
        'dataclasses',
        'enum',
        'pathlib',
        'shutil',
        'subprocess',
        'sys',
        'os',
        'dotenv',
        'ujson',
        'aiohttp',
        'dateparser',
        'colorama',
        'win32_setctime',
        'psutil',
        'rapidocr_onnxruntime',
        'onnxruntime',
        'paddleocr',
        'paddlepaddle',
        'pypdf',
        'youtube_transcript_api',
        'yt_dlp',
        'speech_recognition',
        'pyaudio',
        'pykiwoom',
        'pykiwoom.kiwoom',
        'PyQt5',
        'PyQt5.QtWidgets',
        'PyQt5.QtCore',
        'PyQt5.QtGui',
        'PyQt5.QAxContainer'
    ],
    hookspath=['hooks'],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'matplotlib',
        'scipy',
        'scikit-learn',
        'tensorflow',
        'torch',
        'jupyter',
        'notebook',
        'ipython',
        'pytest',
        'unittest',
        'wx',
        'gtk',
        'qt4',
        'qt6',
        'PyQt6',
        'PySide2',
        'PySide6'
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

# PyQt5/QAxContainer는 Kiwoom OpenAPI+용으로 보존한다. PyQt5-Qt5와
# pandas 하위의 구형 VC DLL만 제거하고 빌드 아키텍처와 같은 공식 VC143 세트를 루트에 둔다.
def _noahai_bundle_basename(entry_name):
    return str(entry_name).replace('\\', '/').rsplit('/', 1)[-1].lower()

def _noahai_is_vc_runtime(entry_name):
    basename = _noahai_bundle_basename(entry_name)
    return basename == 'concrt140.dll' or (
        basename.endswith('.dll')
        and basename.startswith(('msvcp140', 'vcruntime140'))
    )

a.binaries = [
    entry for entry in a.binaries
    if not _noahai_is_vc_runtime(entry[0])
]
a.binaries += [
    (name, source, 'BINARY') for name, source in _noahai_vc_runtime_binaries
]

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)


exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='AITrading',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='icon.ico', # type: ignore
    version='config/windows_version_info.txt',
)
