from __future__ import annotations
from typing import Any, Dict, List, Optional, Tuple
from .exchange_manager import ExchangeManager
from .unified_trading_manager import UnifiedTradingManager

class UnifiedTrader:
    def __init__(self, settings: Dict[str, Any], exchange_manager: Any, unified_manager: Any, analyzer: Optional[Any] = ..., optimizer: Optional[Any] = ..., recorder: Optional[Any] = ..., ai_manager: Optional[Any] = ..., risk_manager: Optional[Any] = ..., websocket_manager: Any | None = ..., dashboard: Any | None = ..., logger: Any | None = ...) -> None: ...

    # Instance attributes (for static analysis)
    exchange_manager: ExchangeManager
    unified_manager: UnifiedTradingManager
    analyzer: Any | None
    optimizer: Any | None
    recorder: Any | None
    ai_manager: Any | None
    risk_manager: Any | None
    dashboard: Any | None
    logger: Any
    monitoring_flags: Dict[str, bool]
    monitoring_threads: Dict[str, Any]
    selected_coins: Dict[str, List[Dict[str, Any]]]
    trade_stats: Dict[str, Dict[str, Any]]
    position_sizing_snapshots: Dict[Any, Any]

    def stop_trading(self, exchange_name: str) -> None: ...
    def set_selected_coins(self, exchange_name: str, selected_coins: List[Dict[str, Any]]) -> None: ...
    def set_evaluator(self, evaluator: Any) -> None: ...
    def set_ai_manager(self, ai_manager: Any) -> None: ...
    def select_trading_coins_unified(self, exchange_name: str) -> List[Dict[str, Any]]: ...
    def start_trading(self, exchange_name: str) -> None: ...

    def _generate_ai_learning_data(self, exchange_name: str, symbol: str, signal_data: Dict[str, Any]) -> None: ...
    def _analyze_pattern_similarity_unified(self, exchange_name: str, symbol: str, analysis: Dict[str, Any]) -> Dict[str, Any]: ...
    def _record_position_with_tp_sl(self, exchange_name: str, symbol: str, signal: str, quantity: float, order_result: Dict[str, Any], optimized_params: Dict[str, Any], execution_mode: str = ...) -> None: ...
    def _perform_pre_entry_analysis_unified(self, exchange_name: str, symbol: str, signal_data: Dict[str, Any]) -> Dict[str, Any]: ...
