// Local synthetic QA only: actual finance/settings components and authenticated test gateway.
import {useState} from 'react';
import {createRoot} from 'react-dom/client';
import {GuidedProductComparison} from '../src/components/GuidedProductComparison';
import {SettingsCenter} from '../src/components/SettingsCenter';
import '../src/styles.css';
async function call(path:string,body?:unknown){const r=await fetch(path,{method:body?'POST':'GET',headers:{Authorization:'Bearer synthetic-v3923-token-for-local-qa-only','Content-Type':'application/json','X-NoahAI-Intent':'confirmed'},body:body?JSON.stringify(body):undefined});if(!r.ok)throw Error('request failed');return r.json();}
const checks:unknown[]=[];Object.assign(window,{financeQaChecks:checks});
const client:any={checkAIProvider:async(provider:string,model:string,capability:string)=>{checks.push({provider,model,capability});return {model_callable:true,catalog_checked:true,requested_model:model,actual_model:model,models:[model]};},settings:()=>call('/api/v1/settings'),updateSettings:(revision:string,changes:any)=>call('/api/v1/settings',{expected_revision:revision,changes}),updateCredentials:(revision:string,provider:string,values:any)=>call('/api/v1/settings/credentials',{expected_revision:revision,provider,values}),settingsDiagnostics:async()=>({}),platform:async()=>({release_version:'3.9.2.4'}),assistantStatus:async()=>({budget:{}}),productIntelligence:(payload?:any)=>call('/api/v1/life-finance/product-intelligence',payload),insuranceWorkspace:(action:string,payload:any)=>call('/api/v1/life-finance/insurance',{action,payload})};
function QA(){const [open,setOpen]=useState(false),[revision,setRevision]=useState(0);return <><main style={{padding:16,height:'100vh',overflow:'auto'}}><p>합성 QA · 실제 API 키·상품 연결 없음</p><GuidedProductComparison client={client} onOpenAISettings={()=>setOpen(true)} settingsRevision={revision}/></main><SettingsCenter client={client} open={open} initialField="ai_provider_profiles.finance_decision.model" onClose={()=>setOpen(false)} onAskAssistant={()=>{}} onSettingsSaved={()=>setRevision(v=>v+1)}/></>}
document.body.style.minWidth='0';createRoot(document.getElementById('root')!).render(<QA/>);
