#!/usr/bin/env python3
"""Export/check the public Strategy Hub venue registry artifact."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from trading.exchanges.venue_capabilities import public_venue_registry


DEFAULT_OUTPUT = ROOT.parent / "daltrading" / "config" / "noahai_venue_registry.json"
DEFAULT_WEB_OUTPUT = ROOT / "webui" / "src" / "generatedVenueRegistry.ts"


def _typescript(registry: dict) -> str:
    payload = json.dumps(registry, ensure_ascii=False, indent=2)
    return (
        "// Generated by scripts/export_strategy_venue_registry.py. Do not edit by hand.\n"
        f"export const VENUE_REGISTRY = {payload} as const;\n"
        "export type PublicVenueProfile = (typeof VENUE_REGISTRY.venues)[number];\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--web-output", type=Path, default=DEFAULT_WEB_OUTPUT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    registry = public_venue_registry()
    expected = json.dumps(registry, ensure_ascii=False, indent=2) + "\n"
    expected_web = _typescript(registry)
    if args.check:
        drift = []
        if not args.output.exists() or args.output.read_text(encoding="utf-8") != expected:
            drift.append(str(args.output))
        if not args.web_output.exists() or args.web_output.read_text(encoding="utf-8") != expected_web:
            drift.append(str(args.web_output))
        if drift:
            print(f"venue registry drift: {', '.join(drift)}", file=sys.stderr)
            return 1
        print(f"venue registry synchronized: {args.output}, {args.web_output}")
        return 0
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(expected, encoding="utf-8", newline="\n")
    args.web_output.parent.mkdir(parents=True, exist_ok=True)
    args.web_output.write_text(expected_web, encoding="utf-8", newline="\n")
    print(args.output)
    print(args.web_output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
