const {chromium}=require('playwright');const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});try{for(const width of [1440,390]){const page=await browser.newPage({viewport:{width,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(String(e)));
await page.goto('http://127.0.0.1:4193/qa/v3923.html');await page.getByText('현재 연결된 검증 상품 자료가 없습니다.',{exact:false}).waitFor();
await page.getByLabel('빌릴 금액',{exact:true}).fill('12000000');await page.getByLabel('기간(개월)',{exact:true}).fill('12');
await page.getByText('기존 대출과 대환 비교',{exact:true}).click();await page.getByLabel('기존 대출 연 금리(%)',{exact:true}).fill('8');await page.getByLabel('기존 대출 중도상환 등 종료 비용(원)',{exact:true}).fill('100000');
const fields=page.locator('fieldset');await fields.nth(0).getByLabel('상품·견적 이름').fill('합성 A');await fields.nth(0).getByLabel('적용 연 금리(%)').fill('4');await fields.nth(0).getByLabel('전체 추가 비용(원)').fill('0');await fields.nth(1).getByLabel('상품·견적 이름').fill('합성 B');await fields.nth(1).getByLabel('적용 연 금리(%)').fill('5');
await page.getByRole('button',{name:'조건 비교·필요한 질문 만들기'}).click();await page.getByRole('heading',{name:'입력 조건에서 먼저 검토할 후보: 합성 A'}).waitFor();assert.equal(await page.getByText('추가 비용 미확인 · 총비용 미확인').count(),1);
await page.getByRole('button',{name:'현재 근거로 다시 진단'}).click();await page.getByRole('heading',{name:'성과 미달 · 엄격 중지'}).waitFor();
await page.getByText('비교 저장·다시 보기 · 암호화 보관함',{exact:true}).click();await page.getByLabel('보관함 비밀번호').fill('synthetic-ui-password-123');await page.getByRole('button',{name:'보관함 열기'}).click();await page.getByRole('button',{name:'현재 조건·결과 저장'}).click();await page.getByRole('button',{name:'저장 결과 보기'}).first().waitFor();await page.screenshot({path:`/tmp/v3923-loan-results-${width}.png`,fullPage:true});await page.getByRole('button',{name:'잠그기',exact:true}).click();await page.getByRole('button',{name:'보관함 열기'}).waitFor();assert.equal(await page.getByRole('button',{name:'저장 결과 보기'}).count(),0);
assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`overflow ${width}`);await page.screenshot({path:`/tmp/v3923-loan-${width}.png`,fullPage:true});assert.deepEqual(errors,[]);await page.close();}
const page=await browser.newPage();await page.goto('http://127.0.0.1:4193/qa/v3923.html?kind=insurance');await page.getByLabel('현재 가입 상태').selectOption('none');await page.getByRole('button',{name:'조건 비교·필요한 질문 만들기'}).click();await page.getByText('보험이 없다면 증권 업로드 없이 필요한 보장부터 정리할 수 있습니다.',{exact:true}).waitFor();await page.getByText('자가용·업무용 운전 중 어느 쪽인가요?',{exact:true}).waitFor();await page.screenshot({path:'/tmp/v3923-insurance.png',fullPage:true});console.log('PASS loan calculations, missing costs, refinance, encrypted save/lock, diagnosis, uninsured driver flow, 1440/390 widths');}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
