const {chromium}=require(process.env.PLAYWRIGHT_MODULE_PATH||'playwright');
const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({headless:true,channel:'chrome'});
 try{for(const width of [1490,1080,640]){
  const page=await browser.newPage({viewport:{width,height:1000}}),errors=[],external=[];
  page.on('pageerror',e=>errors.push(String(e)));page.on('dialog',d=>d.accept());
  page.on('request',r=>{if(!r.url().startsWith('http://127.0.0.1:5173/'))external.push(r.url());});
  await page.goto('http://127.0.0.1:5173/qa/product-guide.html');
  await page.getByRole('heading',{name:'내게 필요한 금융, 한 단계씩'}).waitFor();
  assert.equal((await page.evaluate(()=>window.productQaCalls)).length,0);
  await page.screenshot({path:`/tmp/noah-product-overview-${width}.png`,fullPage:true});
  await page.getByRole('tab',{name:'전체 안내'}).focus();await page.keyboard.press('ArrowRight');
  assert.equal(await page.getByRole('tab',{name:'대출 비교'}).getAttribute('aria-selected'),'true');
  assert.equal(await page.getByLabel('빌릴 금액 (원)',{exact:true}).inputValue(),'');
  await page.getByRole('button',{name:'두 조건 계산하기 · 저장/신청 안 함'}).click();await page.getByRole('alert').waitFor();
  await page.getByRole('button',{name:'가상 예시로 연습'}).click();
  await page.getByRole('button',{name:'두 조건 계산하기 · 저장/신청 안 함'}).click();
  await page.getByRole('heading',{name:'2. 숫자를 읽고 차이 이해하기'}).waitFor();
  assert.equal(await page.locator('.product-flow svg').count(),2);
  await page.screenshot({path:`/tmp/noah-product-loan-${width}.png`,fullPage:true});
  await page.getByLabel('조건 A 추가 비용',{exact:true}).fill('');
  assert.equal(await page.locator('.product-results').count(),0);
  await page.getByRole('button',{name:'두 조건 계산하기 · 저장/신청 안 함'}).click();
  assert.ok((await page.locator('.product-results').innerText()).includes('미확인'));
  await page.getByRole('button',{name:'원리금균등과 원금균등은 어떻게 다른가요?',exact:true}).click();
  assert.equal((await page.evaluate(()=>window.productQaCalls)).length,0);
  await page.getByRole('button',{name:'AI 도움 열기 · 아직 전송하지 않음'}).click();
  await page.locator('.legacy-chat-input input').waitFor();
  assert.equal((await page.evaluate(()=>window.productQaCalls)).length,0,'opening assistant must not send');
  await page.getByRole('button',{name:'전송',exact:true}).click();
  await page.getByText('합성 QA 안내. 실제 외부 AI 호출이 아닙니다.',{exact:true}).waitFor();
  const sent=await page.evaluate(()=>window.productQaCalls[0]);assert.equal(sent.kind,'ask');assert.ok(!sent.question.includes('10000000'));
  await page.getByRole('button',{name:'도움 닫기 · 비교 입력 유지'}).click();
  assert.equal(await page.getByLabel('빌릴 금액 (원)',{exact:true}).inputValue(),'10000000');
  await page.getByRole('tab',{name:'예금·적금 비교'}).click();
  await page.getByRole('button',{name:'가상 예시로 연습'}).click();
  await page.getByRole('button',{name:'두 조건 계산하기 · 저장/신청 안 함'}).click();
  await page.locator('.product-main-number').filter({hasText:'10,253,800원'}).waitFor();
  await page.getByLabel('모으는 방식',{exact:true}).selectOption('installment');
  assert.equal(await page.getByLabel('매달 넣을 금액 (원)',{exact:true}).inputValue(),'');
  await page.getByLabel('매달 넣을 금액 (원)',{exact:true}).fill('100000');
  await page.getByRole('button',{name:'두 조건 계산하기 · 저장/신청 안 함'}).click();
  assert.ok((await page.locator('.product-results').innerText()).includes('19,500원'));
  await page.screenshot({path:`/tmp/noah-product-saving-${width}.png`,fullPage:true});
  await page.getByRole('tab',{name:'보험 비교'}).click();
  await page.getByRole('heading',{name:'내 보험 이해·비교',exact:true}).waitFor();
  await page.getByText('보험 비교 예시 보기 · 내 계약에는 저장하지 않음',{exact:true}).click();
  assert.equal(await page.getByRole('heading',{name:'가상 계약 A',exact:true}).count(),1);
  await page.screenshot({path:`/tmp/noah-product-insurance-${width}.png`,fullPage:true});
  await page.getByRole('tab',{name:'대출 비교'}).click();
  assert.equal(await page.getByLabel('빌릴 금액 (원)',{exact:true}).inputValue(),'10000000');
  await page.getByRole('button',{name:'비우고 내 조건 입력'}).click();
  assert.equal(await page.getByLabel('빌릴 금액 (원)',{exact:true}).inputValue(),'');
  assert.equal(await page.locator('.product-results').count(),0);
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
  assert.deepEqual(errors,[]);assert.deepEqual(external,[]);
  await page.close();console.log(`PASS product guide ${width}px: tabs, examples, calculations, missing data, AI draft/send, retained input, insurance guide`);
 }}finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
