const {chromium}=require('playwright');const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});const page=await browser.newPage({viewport:{width:390,height:1000}});page.setDefaultTimeout(10000);const errors=[];page.on('dialog',d=>d.accept());page.on('pageerror',e=>errors.push(String(e)));
try{
 await page.goto('http://127.0.0.1:4193/qa/v3924-settings.html');
 await page.getByRole('tab',{name:'보험 비교',exact:true}).click();
 const active=()=>page.locator('[role=tabpanel]:visible');
 const question=active().getByLabel('내 상황이나 궁금한 점');
 const sample='차를 몰고 매일 회사에 다녀요. 보험은 없어요.';
 await question.fill(sample);
 await active().getByText('내 말을 AI로 이해하기',{exact:true}).click();
 await active().getByText('설정된 AI의 API 키가 없습니다.',{exact:false}).waitFor();
 assert.equal(await active().locator('.finance-decision select').count(),0);
 assert.equal(await active().getByRole('button',{name:'빠른 판단 기본 모델로 저장'}).count(),0);
 const preview=()=>active().getByRole('button',{name:'질문 분류에 보낼 내용 확인'});
 assert.equal(await preview().isDisabled(),true);
 const count=async()=>(await (await fetch('http://127.0.0.1:3919/qa-counters')).json()).decision;
 const before=await count();
 await active().getByRole('button',{name:'AI 엔진/API 설정 열기'}).click();
 const provider=()=>page.locator('[data-setting-path="ai_provider_profiles.finance_decision.provider"] select');
 const model=()=>page.locator('[data-setting-path="ai_provider_profiles.finance_decision.model"] select');
 await model().waitFor();assert.equal(await model().isDisabled(),true);
 assert.deepEqual(await provider().locator('option').evaluateAll(rows=>rows.map(r=>r.value)),['openai']);
 async function key(providerId){await page.locator('.settings-credential-panel > select').selectOption(providerId);await page.locator('.credential-input-grid input[type=password]').first().fill('synthetic-ui-key');await page.getByRole('button',{name:'새 값 저장',exact:true}).click();await page.getByText('연결 정보 저장·재읽기 검증 완료',{exact:false}).waitFor();}
 await key('deepseek');
 assert.deepEqual((await provider().locator('option').evaluateAll(rows=>rows.map(r=>r.value))).sort(),['deepseek','openai']);
 await provider().selectOption('deepseek');assert.equal(await model().inputValue(),'deepseek-flash');
 assert.equal(await model().isDisabled(),false);
 await page.getByRole('button',{name:'생활금융 선택 모델 연결 점검',exact:true}).click();
 await page.getByText('선택 모델 실제 호출 확인됨',{exact:true}).waitFor();
 assert.deepEqual(await page.evaluate(()=>window.financeQaChecks),[{provider:'deepseek',model:'deepseek-flash',capability:'chat_json'}]);
 assert((await model().locator('option').evaluateAll(rows=>rows.map(r=>r.value))).every(v=>v.startsWith('deepseek')));
 await page.getByRole('button',{name:'선택 모델 1회 실제 호출 점검',exact:true}).click();
 await page.waitForFunction(()=>window.financeQaChecks.length===2);
 assert.deepEqual(await page.evaluate(()=>window.financeQaChecks[1]),{provider:'deepseek',model:'',capability:'chat_text'});
 await page.getByRole('button',{name:'▣ 현재 설정 저장',exact:true}).click();
 await page.getByRole('button',{name:'▣ 현재 설정 저장',exact:true}).waitFor();
 await page.waitForFunction(()=>Array.from(document.querySelectorAll('button')).find(b=>b.textContent==='▣ 현재 설정 저장')?.disabled);
 await page.getByRole('button',{name:'닫기',exact:true}).click();
 await active().getByText('설정된 AI: deepseek · deepseek-flash',{exact:false}).waitFor();
 assert.equal(await question.inputValue(),sample);
 await preview().click();await active().getByText('판단 AI: deepseek · deepseek-flash',{exact:true}).waitFor();assert.equal(await count(),before);
 await active().getByLabel('질문·수신 모델·API 비용 가능성을 확인하고 분류 요청에 동의합니다').check();
 // Changing settings preserves question, but discards its earlier preview/consent.
 await active().getByRole('button',{name:'AI 엔진/API 설정 열기'}).click();await model().waitFor();
 await key('gemini');await provider().selectOption('gemini');assert.equal(await model().inputValue(),'gemini-3.5-flash-lite');
 await page.getByRole('button',{name:'▣ 현재 설정 저장',exact:true}).click();
 await page.waitForFunction(()=>Array.from(document.querySelectorAll('button')).find(b=>b.textContent==='▣ 현재 설정 저장')?.disabled);
 await page.getByRole('button',{name:'닫기',exact:true}).click();
 await active().getByText('설정된 AI: gemini · gemini-3.5-flash-lite',{exact:false}).waitFor();
 assert.equal(await active().getByRole('button',{name:'선택한 AI로 질문 분류',exact:true}).count(),0);
 async function classify(){await preview().click();await active().getByLabel('질문·수신 모델·API 비용 가능성을 확인하고 분류 요청에 동의합니다').check();await active().getByRole('button',{name:'선택한 AI로 질문 분류',exact:true}).click();}
 await classify();await active().getByText('판단한 목적:',{exact:false}).waitFor();assert.equal(await count(),before+1);
 assert.equal(await active().getByRole('button',{name:'이 상황으로 비교·상담 준비하기'}).isDisabled(),true);
 await page.screenshot({path:'reports/v3924-settings-routing-390.png',fullPage:true});
 await active().getByRole('button',{name:'이 해석이 맞아요 · 상황 안내에 적용'}).click();
 await page.waitForFunction(()=>document.querySelector('button[aria-pressed="true"]')?.textContent==='보험이 없어요');
 await question.fill('불확실한 질문입니다');await classify();await active().getByText('목적을 하나로 정하지 않았습니다.',{exact:false}).waitFor();
 assert.equal(await active().getByRole('button',{name:'이 해석이 맞아요 · 상황 안내에 적용'}).count(),0);
 await question.fill('형식오류 시험');await classify();await active().getByText('AI 연결·예산·응답 형식을 확인하지 못해',{exact:false}).waitFor();
 assert.equal(await count(),before+3);
 await page.setViewportSize({width:1440,height:1000});await active().getByRole('button',{name:'AI 엔진/API 설정 열기'}).click();await model().waitFor();
 await page.getByRole('region',{name:'생활금융 빠른 판단 설정 안내'}).scrollIntoViewIfNeeded();
 await page.screenshot({path:'reports/v3924-settings-routing-1440.png',fullPage:true});
 await page.getByRole('button',{name:'연결 삭제',exact:true}).click();await page.getByText('연결 정보를 삭제했습니다.',{exact:true}).waitFor();
 assert.equal(await model().isDisabled(),true);
 await page.getByRole('button',{name:'닫기',exact:true}).click();await active().getByText('설정된 AI의 API 키가 없습니다.',{exact:false}).waitFor();
 assert.equal(await preview().isDisabled(),true);assert.equal(await count(),before+3);
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.deepEqual(errors,[]);
 console.log('PASS settings-only model/key management, no key blocks request, provider-specific choices, setting change invalidates consent and preserves question, JSON dispatch, explicit apply, unknown/malformed fallback, key removal; synthetic adapters only');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
