const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs/promises');
(async()=>{
 const browser=await chromium.launch({channel:'chrome',headless:true});
 const page=await browser.newPage({viewport:{width:390,height:1000}}),errors=[];
 page.on('pageerror',e=>errors.push(String(e)));
 const counters=async()=>JSON.parse(await (await fetch('http://127.0.0.1:3919/qa-counters')).text());
 page.on('dialog',d=>d.accept());
 try{
  await page.goto('http://127.0.0.1:4193/qa/v3923.html?kind=insurance');
  await page.getByLabel('현재 가입 상태').selectOption('none');
  await page.getByLabel('조건 변경 질문').fill('운전자보험에서 먼저 무엇을 확인해야 하나요?');
  await page.getByText('선택한 내용으로 AI 설명 더 보기',{exact:true}).click();
  const before=await counters();
  await page.getByRole('button',{name:'AI에 보낼 내용 먼저 확인'}).click();
  await page.getByText('수신 AI: synthetic · fixture',{exact:true}).waitFor();
  assert.equal((await counters()).ai,before.ai);
  assert.equal(await page.getByRole('button',{name:'선택한 내용 전송·AI 설명 요청'}).isDisabled(),true);
  await page.getByLabel('위 수신 AI·전송 내용·비용 가능성을 확인하고 동의합니다').check();
  await page.getByRole('button',{name:'선택한 내용 전송·AI 설명 요청'}).click();
  await page.getByText('입력한 비교 결과입니다. 추가 비용과 기관 조건을 확인하세요.',{exact:false}).waitFor();
  assert.equal((await counters()).ai,before.ai+1);
  await page.getByLabel('조건 변경 질문').fill('보험 예산 2만원');
  assert.equal(await page.getByRole('button',{name:'선택한 내용 전송·AI 설명 요청'}).count(),0);
  await page.getByText('비교 저장·다시 보기 · 암호화 보관함',{exact:true}).click();
  await page.getByLabel('보관함 비밀번호').fill('synthetic-ui-password-123');
  await page.getByRole('button',{name:'보관함 열기',exact:true}).click();
  await page.getByLabel('상담 수신처',{exact:true}).selectOption('synthetic-manual');
  await page.getByLabel('상담에서 확인하고 싶은 내용').fill('합성 상담 질문');
  await page.getByRole('button',{name:'공유 미리보기 만들기 · 아직 전송 안 함'}).click();
  const manual=page.locator('.finance-consultation article').filter({has:page.getByRole('heading',{name:/시험 상담사 manual/})});
  await manual.getByLabel('위 수신처·목적·공유 내용·보관 안내를 확인하고 동의합니다').check();
  await manual.getByRole('button',{name:'이 내용으로 공유 동의'}).click();
  const downloading=page.waitForEvent('download');
  await manual.getByRole('button',{name:'지정 상담사 전달 자료 받기'}).click();
  const packet=JSON.parse(await fs.readFile(await (await downloading).path(),'utf8'));
  assert.equal(packet.receipt_confirmed,false);assert.deepEqual(packet.packet.scopes,['summary']);
  assert.equal((await counters()).submit,before.submit);
  await manual.getByLabel('상담사가 알려준 접수번호').fill('manual-synthetic-1');
  await manual.getByRole('button',{name:'직접 확인한 접수번호 기록'}).click();
  await manual.getByRole('heading',{name:/기관 검증 전/}).waitFor();
  await page.getByLabel('상담 수신처',{exact:true}).selectOption('synthetic-api');
  await page.getByLabel('이름·연락처·희망 시간',{exact:true}).check();
  await page.getByLabel('상담용 이름').fill('합성 사용자');
  await page.getByLabel('상담용 이메일').fill('synthetic@example.org');
  await page.getByRole('button',{name:'공유 미리보기 만들기 · 아직 전송 안 함'}).click();
  const api=page.locator('.finance-consultation article').filter({has:page.getByRole('heading',{name:/시험 상담사 api/})});
  await api.getByLabel('위 수신처·목적·공유 내용·보관 안내를 확인하고 동의합니다').check();
  await api.getByRole('button',{name:'이 내용으로 공유 동의'}).click();
  await api.getByRole('button',{name:'기관에 상담 요청 전송'}).click();
  await api.getByRole('heading',{name:/기관 접수 확인/}).waitFor();
  assert.equal((await counters()).submit,before.submit+1);
  await page.screenshot({path:'/tmp/v3923-consultation-390.png',fullPage:true});
  await api.getByRole('button',{name:'동의 철회·연락 중단 요청'}).click();
  await api.getByRole('heading',{name:/동의 철회/}).waitFor();
  // The five-second backoff preserves revoked consent without a blind resend.
  await page.getByRole('button',{name:'잠그기',exact:true}).click();
  await page.getByRole('button',{name:'보관함 열기',exact:true}).waitFor();
  assert.equal(await page.getByText('합성 사용자',{exact:false}).count(),0);
  assert.equal(await page.locator('.finance-consultation article').count(),0);
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  assert.deepEqual(errors,[]);
  console.log('PASS explicit AI preview/consent/invalidation, manual packet and reported receipt, API receipt, withdrawal, vault privacy, 390px; synthetic adapters only');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
