const {chromium}=require('playwright');
const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({channel:'chrome',headless:true});
 const page=await browser.newPage({viewport:{width:390,height:950}}),errors=[];
 page.on('pageerror',e=>errors.push(String(e)));page.setDefaultTimeout(10000);
 try {
  const before=await (await fetch('http://127.0.0.1:3919/qa-counters')).json();
  await page.goto('http://127.0.0.1:4193/qa/v3924-settings.html');
  await page.getByRole('tab',{name:'보험 비교',exact:true}).click();
  const directory=page.getByRole('region',{name:'보험회사·상품 둘러보기',exact:true});
  await directory.getByText('공식 안내를 바탕으로 정리한 7개 상품',{exact:false}).waitFor();
  assert.equal(await directory.locator('article').count(),7);
  assert.equal(await page.locator('a[href*="e-insmarket"]').count(),0);
  assert.equal(await page.getByLabel('빠른 판단에 사용할 AI').count(),0);
  await directory.getByLabel('보험회사',{exact:true}).selectOption('삼성화재');
  assert.equal(await directory.locator('article').count(),3);
  await directory.getByLabel('상품·보장 검색').fill('자동갱신형');
  assert.equal(await directory.locator('article').count(),1);
  await directory.getByRole('button',{name:'전체 상품 보기'}).click();
  await directory.getByLabel('보험 종류',{exact:true}).selectOption('driver');
  assert.equal(await directory.locator('article').count(),3);
  await directory.getByLabel('관심 상품 선택 · 무배당 삼성화재 다이렉트 운전자보험',{exact:true}).check();
  await directory.getByLabel('관심 상품 선택 · 현대해상 다이렉트 운전자보험',{exact:true}).check();
  await directory.getByText('삼성화재 상품 상세·확인할 조건',{exact:true}).click();
  await directory.getByRole('region',{name:'관심 상품 비교표',exact:true}).waitFor();
  assert.equal(await directory.getByRole('table').getByRole('columnheader').count(),3);
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  assert.ok((await directory.boundingBox()).width<390);
  assert.equal(await page.locator('main').evaluate(el=>el.scrollWidth>el.clientWidth),false);
  await directory.evaluate(el=>el.scrollIntoView({block:'start'}));
  await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));
  await page.screenshot({path:'reports/v3924-insurance-browser-390.png'});
  await directory.getByRole('region',{name:'관심 상품 비교표',exact:true}).evaluate(el=>el.scrollIntoView({block:'center'}));
  await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));
  await page.screenshot({path:'reports/v3924-insurance-comparison-390.png'});
  const tableRegion=directory.getByRole('region',{name:'관심 상품 비교표',exact:true});
  assert.ok(await tableRegion.evaluate(el=>{el.scrollLeft=el.scrollWidth;return el.scrollLeft>0;}));
  await tableRegion.evaluate(el=>{el.scrollLeft=0;});
  await page.setViewportSize({width:1440,height:1000});
  await directory.evaluate(el=>el.scrollIntoView({block:'start'}));
  await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));
  await page.screenshot({path:'reports/v3924-insurance-browser-1440.png'});
  await directory.getByRole('region',{name:'관심 상품 비교표',exact:true}).evaluate(el=>el.scrollIntoView({block:'center'}));
  await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));
  await page.screenshot({path:'reports/v3924-insurance-comparison-1440.png'});
  await directory.getByLabel('보험 종류',{exact:true}).selectOption('medical');
  await directory.getByLabel('관심 상품 선택 · 현대해상 다이렉트 실손의료비보장보험',{exact:true}).check();
  assert.equal(await directory.getByRole('button',{name:'선택 상품으로 비교·상담 준비',exact:true}).isDisabled(),true);
  await directory.getByLabel('관심 상품 선택 · 현대해상 다이렉트 실손의료비보장보험',{exact:true}).uncheck();
  await directory.getByRole('button',{name:'선택 상품으로 비교·상담 준비',exact:true}).click();
  await page.getByRole('complementary',{name:'상담할 관심 상품'}).waitFor();
  assert.equal(await page.getByLabel('먼저 알아볼 보장').inputValue(),'driver');
  await page.getByRole('button',{name:'조건 비교·필요한 질문 만들기',exact:true}).click();
  await page.getByText('관심 상품 무배당 삼성화재 다이렉트 운전자보험:',{exact:false}).waitFor();
  await page.getByRole('button',{name:'← 상황 안내로 돌아가기 · 비교 입력 유지'}).click();
  assert.equal(await directory.getByRole('table').getByRole('columnheader').count(),3);
  await page.evaluate(()=>window.dispatchEvent(new Event('noah-finance-vault-locked')));
  await directory.getByText('관심 상품 0/4개',{exact:false}).waitFor();
  // Reconfirmation dates and withdrawal are synthetic state transitions only.
  await page.route('**/api/v1/life-finance/product-intelligence',async route=>{
   const response=await route.fetch();const data=await response.json();
   if(data.reference_products)data.reference_products=data.reference_products.map(r=>({...r,evidence_status:'review_due'}));
   await route.fulfill({response,json:data});
  });
  await page.getByRole('button',{name:'아직 잘 모르겠어요',exact:true}).click();
  await directory.getByText('자료 재확인 기한이 지났습니다.',{exact:false}).first().waitFor();
  assert.equal(await directory.getByRole('checkbox').first().isDisabled(),true);
  assert.deepEqual(errors,[]);
  const counters=await (await fetch('http://127.0.0.1:3919/qa-counters')).json();
  assert.equal(counters.submit,before.submit);
  console.log('PASS: 390/1440 internal browse, filters, details, comparison, mixed types, handoff context, lock reset, expiry; no submission');
 } finally {await browser.close();}
})().catch(e=>{console.error(e);process.exit(1)});
