import {useEffect, useRef, useState} from 'react';
import type {GatewayClient} from '../api';

const states:Record<string,string>={prepared:'상담 준비',consented:'공유 동의 완료',package_prepared:'전달 자료 준비 · 접수 미확인',receipt_reported:'접수번호 직접 기록 · 기관 검증 전',submitting:'접수 응답 확인 필요',delivery_unknown:'전송 결과 불명 · 상태 먼저 확인',received:'기관 접수 확인',in_consultation:'상담 진행',closed:'상담 종료',withdrawal_requested:'동의 철회 · 기관 처리 확인 대기',withdrawn:'철회 확인',deleted:'기관 삭제 확인'};
const scopeNames:Record<string,string>={summary:'상담 목적·확인 질문',comparison:'관심 상품·비교 후보·금액·보장·출처',profile:'선택한 금융 조건·예산',contact:'이름·연락처·희망 시간'};
function download(value:unknown,name:string){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download=name;link.click();URL.revokeObjectURL(url);}

export function FinanceConsultation({client,scenario,unlocked,onQuotes}:{client:GatewayClient;scenario:Record<string,any>;unlocked:boolean;onQuotes?:(requestId:string,quotes:any[])=>void}){
 const [recipients,setRecipients]=useState<any[]>([]),[requests,setRequests]=useState<any[]>([]),[recipient,setRecipient]=useState('');
 const [scopes,setScopes]=useState(['summary']),[note,setNote]=useState(''),[contact,setContact]=useState<Record<string,string>>({name:'',phone:'',email:'',preferred_time:''});
 const [reviewed,setReviewed]=useState<Record<string,boolean>>({}),[receipt,setReceipt]=useState<Record<string,string>>({}),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const generation=useRef(0);
 useEffect(()=>{let active=true;void client.insuranceWorkspace?.('finance_handoff',{operation:'recipients'}).then(r=>{if(active)setRecipients(r.recipients);}).catch(()=>{if(active)setError('상담 연결 목록을 읽지 못했습니다. 운영자가 등록한 수신처를 확인하세요.');});return()=>{active=false;};},[client]);
 useEffect(()=>{const revision=++generation.current;setBusy(false);if(!unlocked){setRequests([]);setContact({name:'',phone:'',email:'',preferred_time:''});setNote('');setReviewed({});setReceipt({});return;}void client.insuranceWorkspace?.('finance_handoff',{operation:'list'}).then(r=>{if(revision===generation.current)setRequests(r.requests);}).catch(()=>{if(revision===generation.current)setError('보관함을 다시 열어 상담 기록을 확인하세요.');});return()=>{generation.current++;};},[client,unlocked]);
 async function run(operation:string,extra:Record<string,unknown>={}){const revision=++generation.current;setBusy(true);setError('');try{const r=await client.insuranceWorkspace!('finance_handoff',{operation,...extra});if(revision!==generation.current)return;if(r.download)download(r.download,'상담-선택정보-전달자료.json');const list=await client.insuranceWorkspace!('finance_handoff',{operation:'list'});if(revision===generation.current){setRequests(list.requests);setReviewed({});}}catch{if(revision===generation.current)setError('처리를 완료하지 못했습니다. 수신처·동의·연락처·보관함 잠금을 확인하세요. 전송 결과가 불명확하면 재전송 전에 상태를 조회하고, 재시도 대기 중이면 잠시 후 다시 확인하세요.');}finally{if(revision===generation.current)setBusy(false);}}
 return <section className="panel finance-consultation" tabIndex={-1}><h4>상담 준비·연결·진행 확인</h4><p>선택한 정보만 공유합니다. 건강정보·보험 원문을 자동 첨부하지 않습니다. 상담 접수는 가입 신청이나 계약 체결이 아닙니다.</p>{!unlocked?<p>아래 암호화 보관함을 열면 상담 준비와 진행 기록을 저장할 수 있습니다.</p>:<>
 <label>상담 수신처<select aria-label="상담 수신처" value={recipient} onChange={e=>setRecipient(e.target.value)}><option value="">수신처 미지정 · 준비만 저장</option>{recipients.filter(r=>r.kinds.includes(scenario.kind)).map(r=><option key={r.id} value={r.id}>{r.organization} · {r.name} ({r.mode==='api'?'기관 API':'지정 상담사'})</option>)}</select></label>
 {!recipients.length&&<p>아직 등록된 상담 수신처가 없습니다. 준비 내용은 보관할 수 있으며, 운영자가 지정 상담사 또는 기관 API를 등록한 뒤 연결합니다.</p>}
 {recipients.filter(r=>r.id===recipient).map(r=><div key={r.id}><p>{r.role} · 보관 안내 {r.retention_days}일 · 조건 버전 {r.contract_version}</p><a href={r.privacy_url} target="_blank" rel="noreferrer">수신처 개인정보 처리 안내</a><p>{r.commercial_notice||'제휴·수수료 여부는 수신처 안내에서 확인하세요.'}</p></div>)}
 <fieldset><legend>공유할 항목 선택</legend>{Object.entries(scopeNames).map(([key,label])=><label key={key}><input type="checkbox" checked={scopes.includes(key)} onChange={e=>setScopes(old=>e.target.checked?[...old,key]:old.filter(v=>v!==key))}/>{label}</label>)}</fieldset>
 {scopes.includes('summary')&&<label>상담에서 확인하고 싶은 내용<textarea maxLength={3000} value={note} onChange={e=>setNote(e.target.value)}/></label>}
 {scopes.includes('contact')&&<div className="product-result-grid">{[['name','상담용 이름'],['phone','상담용 전화번호'],['email','상담용 이메일'],['preferred_time','연락 희망 시간']].map(([key,label])=><label key={key}>{label}<input maxLength={200} value={contact[key]} onChange={e=>setContact({...contact,[key]:e.target.value})}/></label>)}</div>}
 <button disabled={busy||!scopes.length} onClick={()=>void run('prepare',{scenario,recipient_id:recipient||null,scopes,contact,note})}>공유 미리보기 만들기 · 아직 전송 안 함</button>
 {requests.filter(r=>r.packet.kind===scenario.kind).map(r=>{const provider=recipients.find(p=>p.id===r.recipient_id);const prior=r.recipient_snapshot;return <article className="panel" key={r.id}><h4>{r.recipient_name} · {states[r.state]||'확인 필요'}</h4><p>준비 {new Date(r.created_at).toLocaleString()} · 선택 항목: {r.packet.scopes.map((s:string)=>scopeNames[s]).join(', ')}</p>
 {r.packet.summary&&<><p>목적: {r.packet.summary.note||'별도 메모 없음'}</p><ul>{r.packet.summary.questions.map((q:string)=><li key={q}>{q}</li>)}</ul></>}
 {r.packet.contact&&<p>연락 정보: {Object.values(r.packet.contact).filter(Boolean).join(' · ')}</p>}
 {r.packet.comparison?.reference_products?.length>0&&<p>공유할 관심 상품: {r.packet.comparison.reference_products.map((p:any)=>`${p.provider||''} ${p.name}`).join(', ')} · 개인 견적 미확인</p>}
 {r.packet.comparison&&<p>공유 후보: {r.packet.comparison.candidates.map((c:any)=>c.name).join(', ')||'없음'}. 선택한 비교에는 입력 금액·보험 보장 메모와 확인 경로가 포함될 수 있습니다.</p>}
 <details><summary>공유할 전체 내용 확인</summary><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{JSON.stringify(r.packet,null,2)}</pre></details>
 {r.state==='prepared'&&r.recipient_id&&<><label><input type="checkbox" checked={!!reviewed[r.id]} onChange={e=>setReviewed({...reviewed,[r.id]:e.target.checked})}/>위 수신처·목적·공유 내용·보관 안내를 확인하고 동의합니다</label><button disabled={busy||!reviewed[r.id]} onClick={()=>void run('consent',{request_id:r.id,payload_hash:r.payload_hash,confirmed:true})}>이 내용으로 공유 동의</button></>}
 {r.state==='consented'&&provider?.mode==='api'&&<button disabled={busy||!r.packet.contact} onClick={()=>{if(window.confirm(`${r.recipient_name}에 위 선택 정보를 보내 상담을 요청할까요?`))void run('submit',{request_id:r.id});}}>기관에 상담 요청 전송</button>}
 {['consented','package_prepared'].includes(r.state)&&provider?.mode==='manual'&&<button disabled={busy} onClick={()=>void run('manual_packet',{request_id:r.id})}>지정 상담사 전달 자료 받기</button>}
 {r.state==='package_prepared'&&<><p>파일을 받은 것만으로 접수되지 않습니다. 지정 상담사에게 직접 전달하고 접수번호를 확인하세요.</p>{provider&&<a href={provider.contact_url} target="_blank" rel="noreferrer">지정 상담사 안내 열기</a>}<label>상담사가 알려준 접수번호<input value={receipt[r.id]||''} onChange={e=>setReceipt({...receipt,[r.id]:e.target.value})}/></label><button disabled={busy||!receipt[r.id]?.trim()} onClick={()=>void run('record_manual_receipt',{request_id:r.id,receipt_id:receipt[r.id],confirmed:true})}>직접 확인한 접수번호 기록</button></>}
 {!provider&&prior&&<p>현재 수신처 등록이 변경되었습니다. 새 전송은 준비 내용을 다시 확인하세요. <a href={prior.contact_url} target="_blank" rel="noreferrer">기존 수신처 안내</a></p>}{r.next_attempt>Date.now()/1000&&<p>다음 기관 확인 가능 시각: {new Date(r.next_attempt*1000).toLocaleString()}. 동의 철회는 대기 중에도 기록됩니다.</p>}{r.receipt&&<p>접수번호: {r.receipt.id} · {r.receipt.basis==='recipient_api'?'수신처 API 확인':'사용자 직접 기록'}</p>}
 {r.result&&<aside><h4>상담 회신 · {r.result.basis==='recipient_api'?'기관 API 확인':'사용자 직접 기록'}</h4><p>담당자: {r.result.assigned_advisor||'배정 미확인'} · 응답 예정: {r.result.expected_reply_at?new Date(r.result.expected_reply_at).toLocaleString():'미확인'}</p>{r.result.quotes?.map((q:any)=><p key={q.id}>{q.provider} {q.name} · 견적 기한 {new Date(q.valid_until).toLocaleString()}</p>)}{r.result.quotes?.length>0&&onQuotes&&<button disabled={busy||['withdrawal_requested','withdrawn','deleted'].includes(r.state)} onClick={()=>{if(window.confirm('표시한 상담 견적을 현재 비교에 추가할까요? 현재 금액·기간과 맞는 조건인지 다시 확인해야 합니다.'))onQuotes(r.id,r.result.quotes);}}>회신 견적을 이 비교에 가져오기</button>}</aside>}
 {['receipt_reported','received','in_consultation','closed'].includes(r.state)&&<details><summary>직접 받은 상담 결과 파일 기록</summary><p>지정 상담사가 제공한 noah 상담 결과 JSON 파일을 선택하세요. API 검증과 구분하여 저장합니다.</p><input type="file" accept="application/json,.json" aria-label="상담 결과 파일" disabled={busy} onChange={async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;if(file.size>128*1024){setError('상담 결과 파일은 128KB까지 지원합니다.');return;}try{const revision=generation.current;const value=JSON.parse(await file.text());if(revision!==generation.current)return;if(window.confirm('직접 받은 상담 결과를 이 접수 기록에 저장할까요? 기존 결과를 대체합니다.'))void run('record_result',{request_id:r.id,result:value,confirmed:true});}catch{setError('상담 결과 JSON 파일 형식을 확인하세요.');}}}/></details>}
 {provider?.mode==='api'&&!['prepared','consented'].includes(r.state)&&<button disabled={busy} onClick={()=>void run('status',{request_id:r.id})}>기관 처리 상태 확인</button>}
 {!['withdrawn','deleted','closed'].includes(r.state)&&<button disabled={busy} onClick={()=>{if(window.confirm('공유 동의를 철회할까요? 이미 전달된 자료의 기관 삭제 완료는 별도로 확인해야 합니다.'))void run('withdraw',{request_id:r.id});}}>동의 철회·연락 중단 요청</button>}
 {provider?.mode==='manual'&&['receipt_reported','withdrawal_requested'].includes(r.state)&&<><label>상담 종료·철회 확인 번호<input value={receipt[r.id]||''} onChange={e=>setReceipt({...receipt,[r.id]:e.target.value})}/></label><button disabled={busy||!receipt[r.id]?.trim()} onClick={()=>{if(window.confirm('상담사가 알려준 처리 결과를 직접 기록할까요? 기관 API 검증이나 자료 삭제 확인과는 다릅니다.'))void run('record_manual_outcome',{request_id:r.id,receipt_id:receipt[r.id],outcome:r.state==='withdrawal_requested'?'withdrawn':'closed',confirmed:true});}}>직접 확인한 종료·철회 결과 기록</button></>}{r.state==='withdrawal_requested'&&<p>앱의 공유 동의는 철회했습니다. 기관의 연락 중단·자료 삭제는 아직 확인되지 않았습니다. 수신처에 처리 결과를 확인하세요.</p>}
 {['prepared','consented','withdrawn','deleted','closed'].includes(r.state)&&<button disabled={busy} onClick={()=>{if(window.confirm('이 PC의 상담 기록을 삭제할까요? 기관에 보관된 정보는 자동 삭제되지 않습니다.'))void run('delete',{request_id:r.id,confirmed:true});}}>로컬 상담 기록 삭제</button>}
 </article>;})}</>}{error&&<p role="alert">{error}</p>}</section>;
}
