import {useEffect,useRef,useState} from 'react';
import type {GatewayClient} from '../api';
export function FinanceLedgerTools({client,onChanged}:{client:GatewayClient;onChanged:()=>void}){
 const [data,setData]=useState<any>(null),[query,setQuery]=useState(''),[start,setStart]=useState(''),[end,setEnd]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[edit,setEdit]=useState<any>(null),[rows,setRows]=useState<any[]|null>(null),[preview,setPreview]=useState<any>(null);const generation=useRef(0);
 async function list(offset=0){const rev=++generation.current;setBusy(true);setError('');try{const r=await client.lifeLedger!({operation:'list',query,start,end,offset});if(rev===generation.current)setData(r);}catch{if(rev===generation.current)setError('거래 기록을 조회하지 못했습니다. 기간을 확인하고 다시 시도하세요.');}finally{if(rev===generation.current)setBusy(false);}}
 useEffect(()=>{if(client.lifeLedger)void list();return()=>{generation.current++;};},[client]);
 if(!client.lifeLedger)return null;
 async function save(){if(!edit)return;setBusy(true);setError('');try{const row={date:edit.date,amount:Number(edit.amount),type:edit.type,description:edit.description,method:edit.method,category:edit.category};if(edit.id)await client.lifeLedger!({operation:'update',id:edit.id,row,expected_revision:edit.revision});else await client.addLifeTransaction(row);setEdit(null);onChanged();await list();}catch{setError('수정하지 못했습니다. 금액·날짜를 확인하세요. 다른 창에서 수정했다면 목록을 다시 조회해야 합니다.');}finally{setBusy(false);}}
 async function importRows(operation:string,value=rows){setBusy(true);setError('');try{const result=await client.lifeLedger!({operation,rows:value,preview_hash:preview?.preview_hash,confirmed:operation==='import'});if(operation==='preview_import')setPreview(result);else{setRows(null);setPreview(null);onChanged();await list();}}catch{setError('가져오기 형식 또는 기존 기록이 변경되었습니다. 파일을 다시 선택해 중복 미리보기를 확인하세요. 이미 저장된 행은 재시도 시 중복으로 제외합니다.');setPreview(null);}finally{setBusy(false);}}
 return <details className="panel product-intelligence"><summary>거래 검색·기간 조회·수정·가져오기</summary><div className="product-result-grid"><label>설명·분류·결제 수단 검색<input value={query} onChange={e=>setQuery(e.target.value)}/></label><label>시작일<input type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><label>종료일<input type="date" value={end} onChange={e=>setEnd(e.target.value)}/></label></div><button disabled={busy} onClick={()=>void list()}>조건으로 조회</button>{busy&&<p role="status">기록을 확인하고 있어요…</p>}{error&&<p role="alert">{error}</p>}{data&&<><p>조회 결과 {data.total}건 · {data.offset+1}번째부터 최대 50건</p>{data.rows.map((r:any)=><article key={r.id}><p>{r.date} · {r.type} · {r.amount.toLocaleString()}원 · {r.description}</p><button disabled={busy} onClick={()=>setEdit({...r})}>수정</button><button disabled={busy} onClick={()=>{const [y,m,d]=r.date.split('-').map(Number);const next=new Date(y,m,Math.min(d,new Date(y,m+1,0).getDate()));const day=`${next.getFullYear()}-${String(next.getMonth()+1).padStart(2,'0')}-${String(next.getDate()).padStart(2,'0')}`;setEdit({...r,id:null,date:day});}}>다음 달 납부 초안</button></article>)}{!data.total&&<p>조건에 맞는 기록이 없습니다. 계좌 잔액이 0원이라는 뜻은 아닙니다.</p>}<button disabled={busy||data.offset===0} onClick={()=>void list(Math.max(0,data.offset-50))}>이전 50건</button><button disabled={busy||data.offset+50>=data.total} onClick={()=>void list(data.offset+50)}>다음 50건</button></>}
 {edit&&<fieldset><legend>{edit.id?'거래 수정':'반복 납부 확인 초안 · 아직 저장 안 함'}</legend>{[['date','날짜'],['amount','금액'],['description','설명'],['method','결제 수단'],['category','분류']].map(([key,label])=><label key={key}>{label}<input type={key==='date'?'date':'text'} value={edit[key]??''} onChange={e=>setEdit({...edit,[key]:e.target.value})}/></label>)}<label>구분<select value={edit.type} onChange={e=>setEdit({...edit,type:e.target.value})}>{['수입','지출','내 계좌 이체'].map(v=><option key={v}>{v}</option>)}</select></label><p>예정 금액을 실제 지출로 자동 기록하지 않습니다. 납부 여부와 같은 날짜의 기존 기록을 확인하세요.</p><button disabled={busy} onClick={()=>void save()}>확인한 기록 저장</button><button disabled={busy} onClick={()=>setEdit(null)}>취소</button></fieldset>}
 <details><summary>JSON 거래 가져오기 · 중복 미리보기</summary><p>최대 300개 거래 배열을 지원합니다. 필수: date(YYYY-MM-DD), amount, type(수입/지출/내 계좌 이체), description. 선택: method, category. 계좌 자동 연동은 아닙니다.</p><input type="file" accept=".json,application/json" aria-label="거래 가져오기 파일" disabled={busy} onChange={async e=>{const file=e.target.files?.[0];e.target.value='';setPreview(null);setRows(null);if(!file)return;if(file.size>512000){setError('파일은 500KB까지 지원합니다.');return;}try{const revision=generation.current;const value=JSON.parse(await file.text());if(revision!==generation.current)return;setRows(value);await importRows('preview_import',value);}catch{setError('JSON 배열 형식을 확인하세요.');}}}/>{preview&&<><p>추가 후보 {preview.rows.length}건 · 중복 제외 {preview.duplicate_rows.length}건</p><ul>{preview.rows.map((r:any,i:number)=><li key={i}>{r.date} {r.description} {r.amount.toLocaleString()}원</li>)}</ul><button disabled={busy||!preview.rows.length} onClick={()=>{if(window.confirm('표시한 중복 제외 거래를 저장할까요?'))void importRows('import');}}>미리본 거래 가져오기</button></>}</details></details>;
}
