import {useEffect,useRef,useState} from 'react';
import type {GatewayClient} from '../api';
const fields:Record<string,string>={monthly_income:'월 소득',monthly_expenses:'월 생활비',other_repayments:'기존 월 상환',insurance_budget:'월 보험료 예산',monthly_saving:'월 저축',target_amount:'목표 금액'};
export function FinanceSharedProfile({client,unlocked,profile,onApply}:{client:GatewayClient;unlocked:boolean;profile:Record<string,any>;onApply:(values:Record<string,any>)=>void}){
 const [saved,setSaved]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);const generation=useRef(0);
 useEffect(()=>{const rev=++generation.current;setSaved(null);setError('');if(unlocked)void client.insuranceWorkspace?.('finance_profile',{operation:'get'}).then(r=>{if(rev===generation.current)setSaved(r.profile);}).catch(()=>{if(rev===generation.current)setError('공통 재무 조건을 읽지 못했습니다.');});return()=>{generation.current++;};},[client,unlocked]);
 async function run(operation:string){const rev=++generation.current;setBusy(true);setError('');try{const r=await client.insuranceWorkspace!('finance_profile',{operation,confirmed:true,profile:operation==='save'?Object.fromEntries(Object.keys(fields).filter(k=>profile[k]!=null&&profile[k]!=='').map(k=>[k,profile[k]])):undefined});if(rev===generation.current)setSaved(r.profile);}catch{if(rev===generation.current)setError('확인한 금액과 보관함 상태를 확인하세요.');}finally{if(rev===generation.current)setBusy(false);}}
 return <details><summary>보험·대출·저축에서 같은 재무 조건 사용</summary><p>직접 확인한 소득·지출·예산만 재사용합니다. 실제 계좌 잔액이나 가계부 기록을 자동으로 합산하지 않습니다.</p>{!unlocked?<p>암호화 보관함을 먼저 열어 주세요.</p>:<>{saved?<><p>확인일 {new Date(saved.confirmed_at).toLocaleString()}</p><ul>{Object.entries(saved.values).map(([k,v])=><li key={k}>{fields[k]}: {Number(v).toLocaleString()}원</li>)}</ul><button disabled={busy} onClick={()=>{if(window.confirm('표시한 저장 조건을 현재 비교의 같은 항목에 반영할까요?'))onApply(saved.values);}}>이 비교에 반영</button><button disabled={busy} onClick={()=>{if(window.confirm('공통 재무 조건을 삭제할까요? 이미 저장한 개별 계획은 유지됩니다.'))void run('reset');}}>공통 조건 초기화</button></>:<p>저장한 공통 조건이 없습니다.</p>}<button disabled={busy} onClick={()=>{if(window.confirm('현재 비교에 입력한 소득·지출·예산을 공통 조건으로 저장할까요? 기존 공통 조건을 대체합니다.'))void run('save');}}>확인한 현재 조건을 공통 조건으로 저장</button></>}{error&&<p role="alert">{error}</p>}</details>;
}
