import { FinanceAIExplanation } from './FinanceAIExplanation';
import { FinanceConsultation } from './FinanceConsultation';
import { FinancialScenarioControls, FinancialScenarioResults, insuranceTypes } from './FinancialScenarioControls';
import './ProductIntelligenceWorkspace.css';
import { useEffect, useRef, useState } from 'react';
import type { GatewayClient } from '../api';
type Kind='loan'|'insurance'|'savings';
const feedStatus:Record<string,string>={current:'갱신됨',refresh_failed:'갱신 실패 · 마지막 자료 보존',paused_after_rollback:'이전 자료 복원 후 자동 갱신 중지',registered:'연결됨'};
const evidenceStatus:Record<string,string>={current:'유효',stale:'기한 지남',withdrawn:'판매 종료'};
const money=(value:unknown)=>typeof value==='number'?`${value.toLocaleString('ko-KR')}원`:'미확인';
type QuoteDraft={name:string;rate:string;fees:string;tax:string;source:string;premium:string;coverage:string;exclusions:string;renewal:string;confirmed:boolean;validUntil:string;conditions:string;institution:string;protected:boolean;eligibleInterest:string;benefits:Record<string,string>};
const blankOffer=():QuoteDraft=>({name:'',rate:'',fees:'',tax:'',source:'',premium:'',coverage:'',exclusions:'',renewal:'',confirmed:false,validUntil:'',conditions:'',institution:'',protected:false,eligibleInterest:'',benefits:{}});
export function ProductIntelligenceWorkspace({client,kind}:{client:GatewayClient;kind:Kind}) {
 const [profile,setProfile]=useState<Record<string,any>>({insurance_state:'unknown',insurance_kind:'driver',method:kind==='loan'?'annuity':'deposit'});
 const [offers,setOffers]=useState([blankOffer(),blankOffer()]);
 const [catalog,setCatalog]=useState<Record<string,any>|null>(null),[result,setResult]=useState<Record<string,any>|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const generation=useRef(0);
 const [question,setQuestion]=useState(''),[answer,setAnswer]=useState(''),[clauses,setClauses]=useState<any[]>([]);
 const [reviews,setReviews]=useState<any[]>([]),[reminder,setReminder]=useState('');
 const [plans,setPlans]=useState<Record<string,any>[]>([]),[password,setPassword]=useState(''),[unlocked,setUnlocked]=useState(false);
 useEffect(()=>{let alive=true;void client.productIntelligence?.().then(r=>{if(alive)setCatalog(r);}).catch(()=>{if(alive)setError('상품 자료를 읽지 못했습니다. 연결 상태를 확인하세요.');});return()=>{alive=false;};},[client]);
 function clearPrivate(){generation.current++;setUnlocked(false);setPlans([]);setReviews([]);setReminder('');setPassword('');setResult(null);setAnswer('');setClauses([]);setQuestion('');setOffers([blankOffer(),blankOffer()]);setProfile({insurance_state:'unknown',insurance_kind:'driver',method:kind==='loan'?'annuity':'deposit'});}
 useEffect(()=>{const clear=()=>clearPrivate();window.addEventListener('noah-finance-vault-locked',clear);return()=>window.removeEventListener('noah-finance-vault-locked',clear);},[kind]);
 useEffect(()=>{if(!unlocked)return;let active=true;const timer=setTimeout(()=>{window.dispatchEvent(new Event('noah-finance-vault-locked'));void client.insuranceWorkspace?.('lock').catch(()=>{});},15*60*1000);const check=()=>{void client.insuranceWorkspace?.('summary').then(r=>{if(active&&r.state!=='unlocked')window.dispatchEvent(new Event('noah-finance-vault-locked'));}).catch(()=>{if(active)clearPrivate();});};const poll=setInterval(check,15000);window.addEventListener('focus',check);return()=>{active=false;clearTimeout(timer);clearInterval(poll);window.removeEventListener('focus',check);};},[unlocked,client,kind]);
 function input(key:string,value:string){generation.current++;setProfile(old=>({...old,[key]:key==='confirmed_conditions'?value.split(',').map(s=>s.trim()).filter(Boolean):value}));setResult(null);setAnswer('');setClauses([]);}
 function offer(index:number,key:keyof QuoteDraft,value:string|boolean|Record<string,string>){generation.current++;setOffers(old=>old.map((r,i)=>i===index?{...r,[key]:value,...(key==='confirmed'?{}:{confirmed:false})}:r));setResult(null);setAnswer('');setClauses([]);}
 const scenario=()=>({kind,profile,offers:offers.filter(r=>r.name||r.rate||r.premium||r.coverage).map(r=>({name:r.name||'받은 조건',source_url:r.source,valid_until:r.validUntil?new Date(r.validUntil).toISOString():undefined,terms:{conditions:r.conditions.split(',').map(v=>v.trim()).filter(Boolean),annual_rate:r.rate,fees:r.fees,tax_rate:r.tax,monthly_premium:r.premium,coverage:r.coverage,exclusions:r.exclusions,renewal:r.renewal,confirmed:r.confirmed,benefits:r.benefits,institution_id:r.institution,protection_scheme:r.protected?'kr_general_deposit':undefined,protection_confirmed:r.protected,eligible_protection_interest:r.eligibleInterest,method:profile.method}}))});
 function loadPlan(p:Record<string,any>){generation.current++;setAnswer('');setClauses([]);setProfile(p.scenario.profile);const restored=p.scenario.offers.map((r:any)=>({...blankOffer(),name:r.name||'',source:r.source_url||'',rate:String(r.terms.annual_rate??''),fees:String(r.terms.fees??''),tax:String(r.terms.tax_rate??''),premium:String(r.terms.monthly_premium??''),coverage:r.terms.coverage||'',exclusions:r.terms.exclusions||'',renewal:r.terms.renewal||'',confirmed:r.terms.confirmed===true,conditions:(r.terms.conditions||[]).join(', '),validUntil:r.valid_until?new Date(new Date(r.valid_until).getTime()-new Date(r.valid_until).getTimezoneOffset()*60000).toISOString().slice(0,16):'',institution:r.terms.institution_id||'',protected:r.terms.protection_confirmed===true,eligibleInterest:String(r.terms.eligible_protection_interest??''),benefits:r.terms.benefits||{}}));while(restored.length<2)restored.push(blankOffer());setOffers(restored.slice(0,20));setResult(p.result);setError(`저장 당시(${p.saved_at}) 결과입니다. 현재 자료로 다시 비교하세요.`);}
 async function compare(){const revision=++generation.current;setBusy(true);setError('');try{const r=await client.productIntelligence!(scenario());if(revision===generation.current)setResult(r);}catch{setError('금액·기간·금리·비용을 확인하세요. 비어 있는 비용과 세율은 미확인으로 처리합니다.');}finally{setBusy(false);}}
 async function dialogue(){const revision=++generation.current;setBusy(true);setError('');try{const r=await client.productIntelligence!({action:'dialogue',scenario:scenario(),question});if(revision!==generation.current)return;setProfile(r.scenario.profile);setResult(r.result);setClauses(r.clauses||[]);setAnswer(r.answer+(r.deltas?.length?'\n'+r.deltas.map((d:any)=>`${d.name}: ${d.before.toLocaleString()}원 → ${d.after.toLocaleString()}원 (차이 ${d.difference.toLocaleString()}원)`).join('\n'):''));}catch{setError('조건 변경을 해석하지 못했습니다. 금액·기간과 바꿀 항목을 명확히 적어주세요.');}finally{setBusy(false);}}
 async function vault(operation:string,id?:string){
  if(busy)return;
  const revision=++generation.current;setBusy(true);setError('');
  try{
   if(operation==='unlock'){
    await client.insuranceWorkspace!('unlock',{password});
    if(revision!==generation.current)return;
    setPassword('');setUnlocked(true);
    const r=await client.insuranceWorkspace!('finance_plan',{operation:'list'});
    if(revision===generation.current){setPlans(r.plans);setReviews(r.reviews||[]);}
   }else if(operation==='lock'){
    await client.insuranceWorkspace!('lock');if(revision===generation.current)window.dispatchEvent(new Event('noah-finance-vault-locked'));
   }else{
    const r=await client.insuranceWorkspace!('finance_plan',{operation,scenario:operation==='save'?scenario():undefined,plan_id:id,reminder_date:operation==='reminder'?reminder:undefined});
    if(revision===generation.current){setPlans(r.plans);setReviews(r.reviews||[]);}
   }
  }catch{if(revision===generation.current){setError('암호화 보관함 작업을 완료하지 못했습니다. 비밀번호·잠금 상태를 확인하세요.');clearPrivate();}}
  finally{setBusy(false);}
 }
 function exportReport(){if(!result)return;const lines=[`# 생활금융 비교·상담 준비`, `작성 ${new Date().toISOString()}`,`규칙 ${result.rule_version}`,`상태 ${result.status}`,`조건부 우선 후보: ${result.best||'미정'}`,`비교 기준: ${result.ranking_basis||'보장·제외·갱신 조건 확인'}`,...result.candidates.map((r:any)=>`\n## ${r.name}\n${JSON.stringify(r,null,2)}`),'\n## 상담 확인 질문',...result.questions.map((q:string)=>`- ${q}`),'\n외부 전송·상담 접수·가입 신청은 실행하지 않았습니다.'];const url=URL.createObjectURL(new Blob([lines.join('\n')],{type:'text/markdown;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='생활금융-비교-상담준비.md';a.click();URL.revokeObjectURL(url);}
 return <section className="panel product-intelligence"><h3>내 상황으로 비교하고 다음 단계 정하기</h3><p>확인된 상품 자료 {catalog?.current_count??'확인 중'}건. {catalog?.status==='source_not_connected'?'현재 연결된 검증 상품 자료가 없습니다. 금융사에서 받은 조건을 아래에 입력해 비교할 수 있습니다.':'유효기간이 지난 자료는 비교 후보에서 제외합니다.'}</p>
 <details><summary>자료 출처·갱신 상태</summary><button disabled={busy} onClick={()=>{setBusy(true);void client.productIntelligence?.({action:'refresh'}).then(setCatalog).catch(()=>setError('자료 갱신에 실패했습니다. 마지막 유효 자료와 만료 시각을 확인하세요.')).finally(()=>setBusy(false));}}>연결된 자료 다시 확인</button>{catalog?.feeds?.map((f:any)=><p key={f.source_id}>{f.source_id}: {feedStatus[f.status]||'상태 확인 필요'} · 연속 실패 {f.failures}회 · 다음 확인 {f.next_attempt?new Date(f.next_attempt*1000).toLocaleString():'대기'}</p>)}{catalog?.products?.filter((r:any)=>r.kind===kind).map((r:any)=><p key={`${r.source_id}:${r.id}`}>{r.provider} {r.name} · {evidenceStatus[r.evidence_status]||'확인 필요'} · 확인 {r.verified_at} · 만료 {r.valid_until} · <a href={r.source_url} target="_blank" rel="noreferrer">원문</a></p>)}<p>개인에게 적용될 금리·보험료·가입 자격은 기관 견적으로 별도 확인합니다.</p></details>
 {kind==='insurance'?<div className="product-result-grid"><label>현재 가입 상태<select value={profile.insurance_state} onChange={e=>input('insurance_state',e.target.value)}><option value="unknown">가입 여부를 잘 모름</option><option value="none">보험 없음</option><option value="existing">가입 보험 있음</option></select></label><label>먼저 알아볼 보장<select value={profile.insurance_kind} onChange={e=>input('insurance_kind',e.target.value)}>{insuranceTypes.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label></div>:<div className="product-result-grid"><label>{kind==='loan'?'빌릴 금액':'예금 원금 / 매월 적금액'}<input inputMode="decimal" value={profile.amount||''} onChange={e=>input('amount',e.target.value)}/></label><label>기간(개월)<input inputMode="numeric" value={profile.months||''} onChange={e=>input('months',e.target.value)}/></label><label>계산 방식<select value={profile.method} onChange={e=>input('method',e.target.value)}>{(kind==='loan'?[['annuity','원리금균등'],['principal','원금균등'],['bullet','만기일시']]:[['deposit','목돈 예금'],['installment','매월 적금']]).map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></label></div>}
 {kind==='loan'&&<details><summary>기존 대출과 대환 비교</summary><p>위 금액·기간에 기존 대출의 남은 원금·기간을 입력하세요. 기본 비교는 같은 상환 방식의 고정 금리 가정이며, 상세 항목에서 기존 계약의 상환 방식을 따로 확인할 수 있습니다.</p><label>기존 대출 연 금리(%)<input value={profile.existing_rate||''} onChange={e=>input('existing_rate',e.target.value)}/></label><label>기존 대출 중도상환 등 종료 비용(원)<input value={profile.existing_exit_fee||''} onChange={e=>input('existing_exit_fee',e.target.value)}/></label></details>}
 <FinancialScenarioControls kind={kind} profile={profile} change={input}/>
 <details open><summary>받은 조건 입력 · 최대 20개</summary><p>실제 견적 수치를 직접 입력하세요. 비어 있는 비용·세율·보장 조건은 0이나 보장 없음으로 간주하지 않습니다.</p><div className="product-result-grid">{offers.map((r,i)=><fieldset key={i}><legend>조건 {i+1}</legend><label>상품·견적 이름<input value={r.name} maxLength={200} onChange={e=>offer(i,'name',e.target.value)}/></label><label>원문 URL 또는 확인 경로<input value={r.source} maxLength={500} onChange={e=>offer(i,'source',e.target.value)}/></label><label>견적 유효 기한 · 확인한 경우 입력<input type="datetime-local" value={r.validUntil} onChange={e=>offer(i,'validUntil',e.target.value)}/></label><label>우대 조건 · 쉼표로 구분<input value={r.conditions} maxLength={2000} onChange={e=>offer(i,'conditions',e.target.value)}/></label>{kind==='insurance'?<><label><input type="checkbox" checked={r.confirmed} onChange={e=>offer(i,'confirmed',e.target.checked)}/>본인 견적의 보험료·보장·제외·갱신 조건을 확인했습니다</label>{String(profile.required_coverages||'').split(',').map(v=>v.trim()).filter(Boolean).map(name=><label key={name}>{name} 지급 조건·한도 근거<input value={r.benefits[name]||''} maxLength={1000} onChange={e=>offer(i,'benefits',{...r.benefits,[name]:e.target.value})}/></label>)}{([['premium','월 보험료(원)'],['coverage','보장·가입금액·지급 조건'],['exclusions','면책·감액·제외 사유'],['renewal','갱신·납입·보장 기간']] as const).map(([key,label])=><label key={key}>{label}<input value={r[key]} maxLength={2000} onChange={e=>offer(i,key,e.target.value)}/></label>)}</>:<><label>적용 연 금리(%)<input value={r.rate} inputMode="decimal" onChange={e=>offer(i,'rate',e.target.value)}/></label>{kind==='loan'?<label>전체 추가 비용(원)<input value={r.fees} inputMode="decimal" onChange={e=>offer(i,'fees',e.target.value)}/></label>:<><label>확인한 이자 세율(%)<input value={r.tax} inputMode="decimal" onChange={e=>offer(i,'tax',e.target.value)}/></label><label>금융회사 식별자 · 보호액 합산용<input value={r.institution} onChange={e=>offer(i,'institution',e.target.value)}/></label><label><input type="checkbox" checked={r.protected} onChange={e=>offer(i,'protected',e.target.checked)}/>일반 예금보호 대상임을 공식 자료에서 확인했습니다</label><label>보호 합산에 쓰는 확인된 소정 이자(원)<input value={r.eligibleInterest} onChange={e=>offer(i,'eligibleInterest',e.target.value)}/></label></>}</>}</fieldset>)}</div><button disabled={busy||offers.length>=20} onClick={()=>{generation.current++;setOffers(old=>[...old,blankOffer()]);setResult(null);}}>견적 추가</button></details>
 {kind!=='insurance' && <details><summary>대출·보험·저축을 함께 감당할 수 있는지 보기</summary><div className="product-result-grid">{[['monthly_income','월 소득'],['monthly_expenses','월 생활비'],['other_repayments','기존 월 상환액'],['insurance_budget','월 보험료 예산'],['monthly_saving','월 저축액']].map(([key,label])=><label key={key}>{label}(원)<input value={profile[key]||''} inputMode="decimal" onChange={e=>input(key,e.target.value)}/></label>)}</div></details>}
 <button disabled={busy||!client.productIntelligence} onClick={()=>void compare()}>조건 비교·필요한 질문 만들기</button>{error&&<p role="alert">{error}</p>}
 {result&&<section aria-live="polite"><h4>{result.best?`입력 조건에서 먼저 검토할 후보: ${result.best}`:kind==='insurance'?'보장 필요부터 확인하세요':'추천을 확정할 근거 확인이 필요합니다'}</h4><p>{result.explanation||result.ranking_basis}</p>{result.priorities&&<ul>{result.priorities.map((s:string)=><li key={s}>{s}</li>)}</ul>}<div className="product-result-grid">{result.candidates.map((r:any,i:number)=><article key={i}><h4>{r.name}</h4>{r.estimate?<><p>연 금리 {r.annual_rate}% · {r.source_kind==='user_quote'?'직접 입력 조건':'출처·권리 검토 등록 자료'}</p><p>원금 {money(r.estimate.principal)} · 전체 이자 {money(r.estimate.interest)}</p>{kind==='loan'?<><p>추가 비용 {money(r.estimate.fees)} · 총비용 {money(r.estimate.total_cost)}</p><p>첫 달 {money(r.estimate.first_payment)} · 마지막 달 {money(r.estimate.last_payment)}</p><p>금리 2%p 상승 가정 최대 월 부담 {money(r.rate_plus_2pp_max_payment)}</p><p>새 상환 반영 후 월 여유: {money(r.remaining_after_new_payment)}</p>{r.refinance&&<p>동일 기간 대환 절감 가정: {money(r.refinance.estimated_saving)}. {r.refinance.assumptions}</p>}<details><summary>월별 상환표</summary><table><thead><tr><th>월</th><th>상환</th><th>이자</th><th>잔액</th></tr></thead><tbody>{r.estimate.schedule.map((s:any)=><tr key={s.month}><td>{s.month}</td><td>{money(s.payment)}</td><td>{money(s.interest)}</td><td>{money(s.balance)}</td></tr>)}</tbody></table></details></>:<><p>세후 이자 {money(r.estimate.net_interest)} · 만기 {money(r.estimate.maturity)}</p><p>{r.estimate.assumptions}</p></>}<p>미확인 우대 조건: {r.unconfirmed_conditions.join(', ')||'입력 없음 · 기관 확인 필요'}</p></>:<><p>월 보험료 {money(r.monthly_premium)}</p><p>보장: {r.coverage||'미확인'}</p><p>제외: {r.exclusions||'미확인'}</p><p>갱신·기간: {r.renewal||'미확인'}</p></>}</article>)}</div>{result.excluded.map((r:any,i:number)=><p key={i}>제외: {r.name} — {r.reason}</p>)}{kind!=='insurance'&&<p>기존 월 예산 차감 후: {money(result.monthly_remaining)}. {result.budget_note}</p>}<FinancialScenarioResults result={result}/><h4>다음에 확인할 질문</h4><ul>{result.questions.map((q:string)=><li key={q}>{q}</li>)}</ul><p>비용·자격·약관을 확인한 뒤 기관에서 개인 견적을 받으세요. 비교만으로 상담 접수나 가입이 이루어지지 않습니다. 아래 상담 준비에서 수신자와 전송 범위를 별도로 확인하세요.</p><button onClick={exportReport}>상담 준비 내용 파일로 받기</button></section>}
 <section className="panel"><h4>내 조건으로 이어서 질문</h4><p>“기간을 24개월로”, “매달 30만원으로”, “보험 예산 2만원”, “카드 조건은 제외”처럼 바꿀 조건을 적으면 현재 입력에 적용해 다시 계산합니다. 자동 저장·가입 신청은 하지 않습니다.</p><label>조건 변경 질문<textarea maxLength={2000} value={question} onChange={e=>setQuestion(e.target.value)}/></label><button disabled={busy||!question.trim()} onClick={()=>void dialogue()}>조건 반영·재계산</button>{answer&&<p style={{whiteSpace:'pre-wrap'}} aria-live="polite">{answer}</p>}{clauses.map((c:any)=><article key={c.product_id+':'+c.chunk_id}><h4>상품 근거: {c.product}</h4><blockquote>{c.text}</blockquote><p>버전 {c.version} · {c.page?`${c.page}쪽`:'쪽수 미기재'} · {c.clause||'조항 미기재'} · 확인 {c.verified_at}</p><a href={c.source_url} target="_blank" rel="noreferrer">원문 확인</a></article>)}</section>
 <FinanceAIExplanation client={client} scenario={scenario()} question={question}/>
 <FinanceConsultation client={client} scenario={scenario()} unlocked={unlocked}/>
 <details><summary>비교 저장·다시 보기 · 암호화 보관함</summary><p>내 보험 보관함과 같은 비밀번호를 사용합니다. 최초 사용은 12자 이상으로 설정하세요. 개인 조건은 암호화하여 이 계정에 저장합니다.</p>{!unlocked?<><input type="password" aria-label="보관함 비밀번호" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="off"/><button disabled={busy||password.length<12||!client.insuranceWorkspace} onClick={()=>void vault('unlock')}>보관함 열기</button></>:<><button disabled={!result||busy} onClick={()=>void vault('save')}>현재 조건·결과 저장</button><button disabled={busy} onClick={()=>void vault('lock')}>잠그기</button><label>다시 점검할 날짜<input type="date" value={reminder} onChange={e=>setReminder(e.target.value)}/></label>{plans.filter(p=>p.scenario.kind===kind).map(p=><p key={p.id}>{p.saved_at} <button disabled={busy||!reminder} onClick={()=>void vault('reminder',p.id)}>이 비교의 재점검일 저장</button> {reviews.find(r=>r.plan_id===p.id)?.reasons.join(' · ')} {p.reminder_date?`재점검 ${p.reminder_date}`:''} <button disabled={busy} onClick={()=>{loadPlan(p);}}>저장 결과 보기</button><button disabled={busy} onClick={()=>{if(window.confirm('이 비교 기록을 삭제할까요?'))void vault('delete',p.id);}}>삭제</button></p>)}</>}</details>
 </section>;
}
