import './ProductIntelligenceWorkspace.css';
import { useState, useEffect, useRef } from 'react';
import type { GatewayClient } from '../api';
const titles: Record<string, string> = { reconciliation_required: '손익 대조 필요', return_evidence_required: '수익률 계산 근거 필요', hard_stop: '손실 보호 중지', strict_stop: '성과 미달 · 엄격 중지', recovery_learning: '위험을 줄여 성과 회복 평가', limited_live_learning: '초기 표본 수집', validated_adaptive: '성과 기준 통과', validation_disabled: '검증 꺼짐' };
const metrics: Record<string,string> = {win_rate:'승률',sharpe:'샤프',mdd:'최대 낙폭',expectancy:'거래당 기대 수익률',walkforward_pass_rate:'거래 구간 안정성'};
export function ProfitabilityDiagnostic({ client, source }: {client: GatewayClient; source: string}) {
 const [report,setReport] = useState<Record<string,any>|null>(null), [error,setError] = useState(''), [busy,setBusy] = useState(false);
 const sequence = useRef(0);
 const [watching,setWatching]=useState(false),[attempt,setAttempt]=useState(0);
 const watcher=useRef(0),timer=useRef<ReturnType<typeof setTimeout>|null>(null);
 function cancelWatch(){watcher.current++;if(timer.current)clearTimeout(timer.current);timer.current=null;setWatching(false);}
 useEffect(()=>{cancelWatch();setAttempt(0);return()=>{watcher.current++;if(timer.current)clearTimeout(timer.current);};},[source]);
 async function watch(){cancelWatch();const token=watcher.current;setWatching(true);setAttempt(0);const delays=[5000,10000,20000];async function run(index:number){if(token!==watcher.current)return;setAttempt(index+1);try{const data=await client.profitabilityDiagnostic!(source);if(token!==watcher.current)return;setReport(data);if(!data.recovery?.automatic_local_recheck_allowed||index===2){setWatching(false);return;}}catch{if(token!==watcher.current)return;setError('재진단에 실패했습니다. 연결 상태와 진단 자료를 확인하세요.');if(index===2){setWatching(false);return;}}timer.current=setTimeout(()=>void run(index+1),delays[index+1]);}timer.current=setTimeout(()=>void run(0),delays[0]);}
 useEffect(() => { sequence.current++; setReport(null); setError(''); setBusy(false); return () => {sequence.current++;}; }, [source]);
 async function check() { cancelWatch();const id=++sequence.current; setBusy(true);setError(''); try { const data=await client.profitabilityDiagnostic!(source);if(id===sequence.current)setReport(data); } catch {if(id===sequence.current)setError('진단 근거를 읽지 못했습니다. 로그인·엔진 연결 상태를 확인하고 다시 시도하세요.');} finally {if(id===sequence.current)setBusy(false);} }
 function exportDiagnostic(){if(!report)return;const safe=Object.fromEntries(['source','status','evaluated_at','diagnostic_state','sample_scope','sample_days','sample_limit','raw_trade_rows','total_trades','unresolved_trades','excluded_return_rows','criteria','policy_origins','available_actions','reasons','recovery'].map(key=>[key,report[key]]));const data={format:'noah-profitability-diagnostic-v1',...safe,policy_mode:report.effective_policy?.underperformance_mode,orders_submitted:false,credentials_included:false,trade_records_included:false};const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='noah-profitability-diagnostic.json';a.click();URL.revokeObjectURL(url);}
 return <section className="panel profitability-diagnostic"><h4>수익성 진단 · {source.toUpperCase()}</h4><p>거래 기록을 삭제하지 않고 현재 엔진의 적용 정책과 확정 성과를 다시 계산합니다.</p><button disabled={busy || !client.profitabilityDiagnostic} onClick={()=>void check()}>{busy?'확인 중…':'현재 근거로 다시 진단'}</button>{report?.recovery?.automatic_local_recheck_allowed&&!watching&&<button disabled={busy} onClick={()=>void watch()}>현재 근거 자동 재확인 · 최대 3회</button>}{watching&&<button onClick={cancelWatch}>자동 재확인 취소</button>}{attempt>0&&<p>이번 재확인 {attempt}/3회 · {watching?'제한된 간격으로 확인 중':'확인 종료'}. 거래 재개·주문은 별도 운용 조건을 따릅니다.</p>}{error && <p role="alert">{error}</p>}{report && <div aria-live="polite"><h4>{titles[report.diagnostic_state] || report.message}</h4>{report.recovery&&<details><summary>원인별 복구·재개 조건</summary>{report.recovery.reasons.map((r:any)=><p key={r.reason}>{r.title}: {r.resume_condition}</p>)}<p>{report.recovery.note}</p></details>}{report.status==='evaluated' && <><button onClick={exportDiagnostic}>진단 요약 파일로 받기</button><p>원인·기준·정책 출처만 담습니다. 계좌 식별자·API 키·개별 거래는 포함하지 않습니다.</p><p>{report.sample_days == null ? '현재 보관 기간' : `최근 ${report.sample_days}일`} · 최대 {report.sample_limit}건 · 읽은 기록 {report.raw_trade_rows}건 · 계산 표본 {report.total_trades}건. 범위: {report.sample_scope==='paper_closed_trades'?'PAPER 청산 거래':report.sample_scope==='live_closed_trades'?'LIVE 확정 완료 거래':report.sample_scope==='mock_closed_trades'?'모의 거래':'진단 자료'}.</p><p>정책: {report.effective_policy.underperformance_mode} · 출처: {report.policy_origins.underperformance_mode}. 미대조 {report.unresolved_trades ?? 0}건 · 수익률 근거 제외 {report.excluded_return_rows ?? 0}건.</p><table><thead><tr><th>검사</th><th>실제</th><th>기준</th></tr></thead><tbody>{report.criteria.map((row:any,i:number)=><tr key={i}><td>{metrics[row.metric] || row.metric}{i===5?' (보호 한도)':''}</td><td>{row.actual ?? '계산 전'}</td><td>{row.operator} {row.threshold}</td></tr>)}</tbody></table><p>비율 수치는 0.30 = 30%입니다. 낙폭은 거래별 수익률을 복리 누적한 판정값이며 실제 계좌 잔고 손실률과 다릅니다. 거래 구간 안정성은 재학습한 외부 검증 결과가 아닙니다.</p>{['reconciliation_required','return_evidence_required'].includes(report.diagnostic_state) ? <p>아래 거래 기록 점검·복구를 실행하고, 빠진 근거가 있으면 원본 명세서를 대조한 뒤 다시 진단하세요.</p> : report.diagnostic_state==='strict_stop' ? <p>고급 매매 계층의 성과 미달 처리 정책을 검토하세요. 제한 회복을 선택해도 손실 보호·손익 대조·계좌 위험 검사를 통과해야 합니다. 거래소별 정책은 전역 설정보다 우선합니다.</p> : report.diagnostic_state==='hard_stop' ? <p>손실 한도를 초과했습니다. 전략과 기록을 검토하고 PAPER에서 검증하세요. 초기화·재시작은 손실 근거를 지우거나 실거래를 허용하지 않습니다.</p> : <p>엔진은 매 주기·청산 후 성과를 다시 평가합니다. 이 진단은 신규 주문이나 거래 시작 명령이 아닙니다.</p>}</>}</div>}</section>;
}
